### ISSUE TITLE
Point 2023.p.o at unique-dragon-f0bac4.netlify.app

### ISSUE THREAD

**Issue by doismellburning** [PyconUK/2023.pyconuk.org#1]

**Comment by doismellburning** [comment]
https://unique-dragon-f0bac4.netlify.app/ until then...!

**Comment by geokala** [comment]
@doismellburning This looks to already have been done? 
`2023.pyconuk.org.	3600	IN	CNAME	unique-dragon-f0bac4.netlify.app.`

Is this good to be closed?

**Comment by doismellburning** [comment]
Whoops, yes, thanks
